{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## dio-java-basico\n",
    "\n",
    "Bem-vindo ao repositório `dio-java-basico`! Este repositório contém todo o código-fonte desenvolvido durante o curso de Java Básico oferecido pela Digital Innovation One (DIO).\n",
    "\n",
    "## Índice\n",
    "\n",
    "- [Sobre o Curso](#sobre-o-curso)\n",
    "- [Estrutura do Repositório](#estrutura-do-repositório)\n",
    "- [Pré-requisitos](#pré-requisitos)\n",
    "- [Como Usar](#como-usar)\n",
    "- [Contribuição](#contribuição)\n",
    "\n",
    "## Sobre o Curso\n",
    "\n",
    "O curso de Java Básico da DIO tem como objetivo ensinar os fundamentos da linguagem de programação Java. Durante o curso, são abordados conceitos essenciais como:\n",
    "\n",
    "- Anatomia das Classes\n",
    "- Variáveis e Tipos de Dados\n",
    "- Operadores\n",
    "- Controle de Fluxo\n",
    "- Estruturas de Dados\n",
    "- Programação Orientada a Objetos (POO)\n",
    "- Tratamento de Exceções\n",
    "\n",
    "## Estrutura do Repositório\n",
    "\n",
    "A estrutura do repositório é organizada de acordo com os módulos e aulas do curso:\n",
    "\n",
    "```sh\n",
    "dio-java-basico/\n",
    "├── 01-anatomia-classes/\n",
    "│ ├── ExemploAnatomia.java\n",
    "├── 02-variaveis-tipos-dados/\n",
    "│ ├── ExemploVariaveis.java\n",
    "│ ├── ExemploTiposDados.java\n",
    "│ └── ... \n",
    "├── 03-operadores/\n",
    "│ ├── ExemploOperadores.java\n",
    "│ └── ...\n",
    "├── 04-controle-fluxo/\n",
    "│ ├── ExemploIfElse.java\n",
    "│ └── ...\n",
    "├── 05-estruturas-dados/\n",
    "│ ├── ExemploArrays.java\n",
    "│ └── ...\n",
    "├── 06-poo/\n",
    "│ ├── ExemploClasses.java\n",
    "│ ├── ExemploHeranca.java\n",
    "│ └── ...\n",
    "├── 07-excecoes/\n",
    "│ ├── ExemploTryCatch.java\n",
    "│ └── ...\n",
    "└── README.md\n",
    "```\n",
    "\n",
    "## Pré-requisitos\n",
    "\n",
    "Para executar os exemplos de código deste repositório, você precisará ter o seguinte instalado em sua máquina:\n",
    "\n",
    "- [Java Development Kit (JDK)](https://www.oracle.com/java/technologies/javase-jdk11-downloads.html) - versão 11 ou superior\n",
    "- Um ambiente de desenvolvimento integrado (IDE) como [IntelliJ IDEA](https://www.jetbrains.com/idea/), [Eclipse](https://www.eclipse.org/), [NetBeans](https://netbeans.apache.org/front/main/download/nb18/) ou [Visual Studio Code](https://code.visualstudio.com/download).\n",
    "\n",
    "## Como Usar\n",
    "\n",
    "1. Clone este repositório para a sua máquina local:\n",
    "  ```sh\n",
    "   git clone https://github.com/nathaliacappellini/dio-java-basico.git\n",
    "  ```\n",
    "2. Navegue até o diretório do repositório clonado:\n",
    "  ```sh\n",
    "  cd dio-java-basico\n",
    "  ```\n",
    "3. Abra o projeto em sua IDE preferida.\n",
    "\n",
    "4. Navegue até o arquivo Java que deseja executar.\n",
    "\n",
    "5. Compile e execute o arquivo diretamente da sua IDE.\n",
    "\n",
    "## Contribuição\n",
    "Contribuições são bem-vindas! Se você deseja melhorar o conteúdo deste repositório, siga os passos abaixo:\n",
    "\n",
    "1. Faça um fork deste repositório.\n",
    "\n",
    "2. Crie uma nova branch com a sua feature ou correção de bug:\n",
    "  ```sh\n",
    "  git checkout -b minha-feature\n",
    "  ```\n",
    "3. Faça as modificações necessárias e commit:\n",
    "  ```sh\n",
    "  git commit -m 'Minha nova feature'\n",
    "  ```\n",
    "4. Envie para o seu repositório forkado:\n",
    "  ```sh\n",
    "  git push origin minha-feature\n",
    "  ```\n",
    "5. Abra um Pull Request descrevendo as mudanças propostas.  \n",
    "---\n",
    "  \n",
    "Esperamos que este repositório seja útil para os seus estudos e que você aproveite ao máximo o curso de Java Básico! Se tiver alguma dúvida, sinta-se à vontade para abrir uma issue. Bons estudos! 🌟"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
